# Site settings
title: Elçin Ekşi
email: elcineksi@gmail.com
description: "kişisel"
baseurl: ""
url: "http://elcineksi.xyz"
username: elcineksi

# Build settings
markdown: kramdown
#permalink: pretty
highlighter: rouge
paginate: 5
paginate_path: "/sayfa:num"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
